services:
  petclinic:
    image: youssif37/petclinic
    ports:
      - "8081:8080"
    environments:
      - SPRING_PROFILES_ACTIVE=postgres
      - POSTGRES_USER=petclinic
      - POSTGRES_PASS=petclinic
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/petclinic

    depends_on:
      - postgres
  postgres:
    image: postgres:17.0
    ports:
      - "5432:5432"
    environments:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
